StatiDisc/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [

    url(r'^courses/', include('courses.urls', namespace='courses')),

    url(r'^rounds/', include('rounds.urls', namespace='rounds')),

    url(r'^scorecards/', include('scorecards.urls', namespace='scorecards')),

    url(r'^admin/', admin.site.urls),

    url(r'^users/', include('users.urls', namespace='users')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scorecards/urls.py
from django.conf.urls import url

from . import views

app_name='scorecards'

urlpatterns = [
    
    # scorecards/
    url(r'^$', views.scorecards, name='scorecards'),

    # scorecards/fill_scorecard/$
    url(r'^fill_scorecard/$', views.fill_scorecard, name='fill_scorecard'),

    # scorecards/scorecarddetails/5/$
    url(r'^scorecarddetails/(?P<pk>\d+)/$', views.scorecarddetails, name='scorecarddetails'),

    # scorecards/5/select_round/$
    url(r'^(?P<pk>\d+)/select_round/$', views.select_round, name='select_round'),

    # scorecards/select_course/$
    url(r'^select_course/$', views.select_course, name='select_course'),
    ]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'users'
urlpatterns = [
    # users/signup
    url(r'^signup/$', views.signup, name='signup'),

    # users/auth_user
    url(r'^auth_user', views.auth_user, name='auth_user'),

    # users/auth_user_logout
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    #users/5/profile
    url(r'^(?P<pk>\d+)/profile/$', views.profile_page, name='profile'),

    # users/social
    url(r'^social/$', views.social, name='social'),

    # users/add_friend
    url(r'^add_friend/$', views.add_friend, name='add_friend'),

    ]

scorecards/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

from courses.models import Course, Hole
from rounds.models import Round

# Define the Scorecard model, which has a course and can own several holes and scores
class Scorecard(models.Model):
    # TODO : Add user owner!

    round = models.ForeignKey('rounds.Round', on_delete=models.CASCADE, null = True) 
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null = True) # Foreign key for a scorecard is a single course
    date_played = models.DateField(default=date.today, null=True) # Date the scorecard was created
    noOfHoles = models.PositiveIntegerField(null = True) # Number of holes played on the card
    total_score = models.PositiveIntegerField(null = True) # Sum of all scores for a scorecard, can be set via get_total_score
    user = models.ForeignKey(User, on_delete=models.CASCADE, null = True) # Owner/owners of scorecard

    def get_absolute_url(self):
        return reverse('scorecards:scorecards')

    # Function to get the total score for a scorecard
    def get_total_score(self):
        total_score = 0
        for a_score in self.score_set.all():
            total_score += a_score.score
        return total_score

    # Function to get number of holes played on a scorecard
    def get_noOfHoles(self):
        noOfHoles = 0
        for round in self.round.holes.all():
            noOfHoles += 1
        return noOfHoles

    # Function to get total score, looping over all score objects
    def get_total_score(self):
        total_score = 0
        for score in self.score_set.all():
            total_score = score.score
        return total_score
    
# Define the Score model, which is just a value(score) on a hole represented in a scorecard
class Score(models.Model):
    score = models.PositiveIntegerField(null = True) # A score value for this score
    scorecard = models.ForeignKey(Scorecard, on_delete=models.CASCADE, null = True) # A scorecard can own several scores
    hole = models.ForeignKey(Hole, on_delete=models.CASCADE, blank=True, null=True) # A hole can have several scores for it

scorecards/forms.py
from django import forms
from django.forms import ModelForm, ModelMultipleChoiceField, BaseForm, Form
from django.forms.formsets import BaseFormSet

from .models import Scorecard, Score
from courses.models import Hole

class ScoreForm(Form):
    score = forms.IntegerField(min_value = 1)

scorecards/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.forms import ModelForm
from django.urls import reverse_lazy, reverse
from django_tables2 import RequestConfig
from django.forms.models import modelformset_factory, formset_factory
import datetime

from .models import Score, Scorecard
from .forms import ScoreForm
from courses.models import Course, Hole
from rounds.models import Round
from courses.forms import HoleForm
from rounds.forms import RoundForm
from courses.tables import CourseTable, HoleTable
from .tables import ScoreCardTable, ScoreTable, ScoreCardTableMini
from rounds.tables import RoundTable

# Render list of scorecards
def scorecards(request):
    scorecards = Scorecard.objects.filter(user = request.user)
    courses = Course.objects.all()

    return render(request, 'scorecards/scorecards.html', {'scorecards': scorecards, 'courses': courses})

# Details for a scorecard
def scorecarddetails(request, pk):
    scorecard = Scorecard.objects.get(id = pk)
    scores = Score.objects.filter(scorecard = scorecard)
    course = scorecard.course
    holes = scorecard.round.holes.all()

    context = {
               'scores': scores, 
               'scorecard': scorecard,
               'holes': holes,
               }
    return render(request, 'scorecards/scorecarddetails.html', context)

# Creating a scorecard without going from a course detailview, first #
# select course, then round #
def select_course(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            course_name = request.POST.get('selected_course')
            course = Course.objects.get(course_name = course_name)
            pk = course.pk
            return redirect('scorecards:select_round', pk = pk)
        else:
            courses = Course.objects.all()
            return render(request, 'scorecards/select_course.html', {'courses': courses})
    else:
        error = 'You have to log in before creating a scorecard!'
        return render(request, 'scorecards/error.html', {'error': error})


# Fill out scorecard with POST data
def fill_scorecard(request):
    ScoreFormSet = formset_factory(ScoreForm)
    if request.method == "POST":
        # Create formset from the data available in the POST
        formset = ScoreFormSet(request.POST)
        if formset.is_valid():
            course = Course.objects.get(course_name = request.POST.get('course')) # Get course
            round = Round.objects.get(name = request.POST.get('round'), course = course) # Get round
            holes = round.holes.all()
            user = request.user

            i = 0
            total_score = 0
            scores = []

            # Loop over all forms in formset
            for form in formset:
                score = Score()
                score.score = form.cleaned_data.get('score')
                score.hole = holes[i]
                total_score += score.score
                i += 1
                scores.append(score)

            # Create a scorecard object without scores
            scorecard = Scorecard(round = round, course = course, total_score = total_score, date_played = datetime.date.today(), noOfHoles = i, user = user)
            scorecard.save()

            # Assign each score to the scorecard
            for score in scores:
                score.scorecard = scorecard
                score.save()

            # For now just pass to index page
            courses = CourseTable(Course.objects.all())
            RequestConfig(request).configure(courses)

            if request.user.is_authenticated:
                user = request.user

            noOfRounds = user.profile.get_no_of_rounds()
            scorecards = user.scorecard_set.order_by('-date_played')[0:4]
            most_played, times = user.profile.get_most_played_course()

            recent_scorecards = ScoreCardTableMini(scorecards)
            RequestConfig(request).configure(recent_scorecards)

            context = {'courses': courses, 
                       'noOfRounds': noOfRounds,
                       'recent_scorecards': recent_scorecards,
                       'most_played': most_played,
                       'times': times,
                       }
            return render(request, 'courses/index.html', context)
    else:
        course = request.POST.get('course')
        round_name = request.POST.get('selected_round') # Why does this return a string and not a Round object?

        # Get round and course
        course = Course.objects.get(course_name=course)
        round = Round.objects.get(name=round_name, course = course) # Okay get the actual round
        holes = round.holes.all()

        # Create Formset
        ScoreFormSet = formset_factory(ScoreForm, fields = ('score',))
        score_formset = ScoreFormSet()

        context = {
            'round': round,
            'course': course,
            'formset': score_formset,
            'holes': holes,
            }
        
        return render(request, 'scorecards/fill_scorecard.html', context)


# Pick round for scorecard creation
def select_round(request, pk):
    if request.user.is_authenticated:
        if request.method == "POST":
            # THIS PART IS NOT USED, REDIRECTS TO FILL_SCORECARD WITH GET #

            course = request.POST.get('course')
            round_name = request.POST.get('selected_round') # Why does this return a string and not a Round object?

            # Get round and course
            course = Course.objects.get(course_name=course)
            round = Round.objects.get(name=round_name, course = course) # Okay get the actual round
            holes = round.holes.all()

            # Create Formset
            ScoreFormSet = formset_factory(ScoreForm, extra = len(round.holes.all()))
            score_formset = ScoreFormSet()

            context = {
                'round': round,
                'course': course,
                'formset': score_formset,
                'holes': holes,
                }
        
            return render(request, 'scorecards/fill_scorecard.html', context)
        else:
            course = Course.objects.get(id = pk)
            rounds = course.round_set.all() # Get rounds for course
            context = {
                'rounds': rounds,
                'course': course
                }
            return render(request, 'scorecards/select_round.html', context)
    else:
        error = 'You have to log in before creating a scorecard!'
        return render(request, 'scorecards/error.html', {'error': error})

# SECTION FOR NEW IMPROVED SCORECARD RENDERING AND POSTING #

# Handle course and round selection in one complete view
def selection(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            raise NotImplementedError('Not made this yet')
        else:
            courses = Course.objects.all()
            rounds = Round.objects.all()

            context = {
                'rounds': rounds,
                'courses': courses,

                }

scorecards/templates/scorecards/error.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Error!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>

    {% block content %}

    <div class="row">
        <div class="col">
            <div class="alert alert-danger">
                {{ error }}
            </div>
        </div>
    </div>

    {% endblock %}
</body>
</html>

scorecards/templates/scorecards/fill_scorecard.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}

    <h3>Scorecard for {{ round.name }} at {{ course.course_name }}</h3>

    <hr />

    <form action="{% url 'scorecards:fill_scorecard' %}" method="POST">
        {% csrf_token %}

        <!-- Style for table -->
        <style scoped>
            table, th, td {
                text-align: center;
                border: groove;
            }

            input {
                width: 50px;
            }
        </style>

        {{ formset.management_form }}
        <table id="formset" class="form">
            <!-- Row for hole number -->
            <tr>
                <th>
                    <b>Hole</b>
                </th>
                {% for hole in holes %}
                <th>
                    {{ hole.hole_number }}
                </th>
                {% endfor %}
            </tr>
            <!-- Row for hole par -->
            <tr>
                <td>
                    <b>Par</b>
                </td>
                {% for hole in holes %}
                <td>
                    {{ hole.hole_par }}
                </td>
                {% endfor %}
            </tr>
            <!-- Row for Scoreforms -->
            <tr>
                <td>
                    <b>Score</b>
                </td>
                {% for form in formset.forms %}
                    {% for field in form.visible_fields %}
                    <td>
                        {{ field }}
                    </td>
                    {% endfor %}
                    <!-- For id form -->
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                {% endfor %}
            </tr>
        </table>

        <input type="hidden" name="round" value="{{ round }}" />
        <input type="hidden" name="course" value="{{ course }}"/>

        <input class="btn btn-primary" type="submit" value="Submit!" style="margin-top: 10px; width: 100px"/>

    </form>
    
    {% endblock %}
</body>
</html>

scorecards/templates/scorecards/scorecard_error.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}

    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endif %}
    
    {% endblock %}
</body>
</html>

scorecards/templates/scorecards/scorecard_form.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    {% block javascript %}
    <!-- Event listener for id_course dropdown -->
    <script>
        $(document).ready(function() {

            $('#id_course').on( 'click', function() {
                alert('Listener called');
            });

        });

    </script>


    {% endblock %}

</head>
<body>

    {% block content %}

    <h3>Create a new scorecard:</h3>

    <hr />

    <form action="" method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Create!" />
    </form>

    {% endblock %}
</body>
</html>

scorecards/templates/scorecards/scorecarddetails.html
<!DOCTYPE html>

    {% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="utf-8" />
	<title>Scorecard</title>

	{% load render_table from django_tables2 %}

</head>
<body>

	{% block content %}

	<h2>Round at {{ scorecard.course.course_name }}, {{ scorecard.date_played }}</h2>

    <!-- Style for table -->
    <style scoped>
        table, th, td {
            border: groove;
        }

        td, th {
            width: 50px;
            text-align: center;
        }

    </style>

    <table>
        <!-- Row for hole number -->
        <tr>
            <th>
                <b>Hole</b>
            </th>
            {% for hole in holes %}
            <th>
                {{ hole.hole_number }}
            </th>
            {% endfor %}
            <th>
                Total
            </th>
        </tr>
        <!-- Row for hole par -->
        <tr>
            <td>
                <b>Par</b>
            </td>
            {% for hole in holes %}
            <td>
                {{ hole.hole_par }}
            </td>
            {% endfor %}
            <!-- Column for total par -->
            <td>
                {{ scorecard.round.total_par }}
            </td>
        </tr>
        <!-- Row to show score -->
        <tr>
            <td>
                <b>Score</b>
            </td>
            {% for score in scores %}
            <td>
                {{ score.score }}
            </td>
            {% endfor %}
            <!-- Column for total score -->
            <td>
                {{ scorecard.total_score }}
            </td>
        </tr>
    </table>

	{% endblock %}
</body>
</html>

scorecards/templates/scorecards/scorecards.html
<!DOCTYPE html>

    {% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Courses</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
    
    {% block content %}

	<h2>Your scorecards:</h2>

    <div id="accordion">
        {% for course in courses %}
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#{{ course.course_name }}" aria-expanded="true" aria-controls="collapseOne">
                        {{ course.course_name }}
                    </button>
                </h5>
            </div>

            <div id="{{ course.course_name }}" class="collapse hide" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <div class="row .fluid">
                        {% for scorecard in scorecards %}
                        {% if scorecard.course == course %}
                        <div class="col-sm-3">
                            <div class="card card-body" style="margin-bottom: 5px">
                                <p>Round: {{ scorecard.round }}</p>
                                <p>Score: {{ scorecard.total_score }}</p>
                                <p>Date played: {{ scorecard.date_played }}</p>
                                <a href="{% url 'scorecards:scorecarddetails' pk=scorecard.id %}" class="btn btn-primary">View</a>
                            </div>
                        </div>

                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
	
    {% endblock %}
</body>
</html>

scorecards/templates/scorecards/select_course.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <script>
        $(document).ready(function () {
            $(document).on('click', '#send', function () {
                $('#submit').val(data)
                document.forms["myForm"].submit();
            })
        })
    </script>


    {% block content %}

    <h3>Select course:</h3>

    <hr />

    <form action="." method="POST">
        {% csrf_token %}

        <select name="selected_course">
            {% for course in courses %}
            <option value="{{ course }}">{{ course.course_name }}</option>
            {% endfor %}
        </select>

        <br />

        <input class="btn btn-primary" type="submit" value="Select round!" style="margin-top: 10px"/>

    </form>
    
    {% endblock %}
</body>
</html>

scorecards/templates/scorecards/select_round.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}
{% load static %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Round select</title>

    <link rel="stylesheet" type="text/css" href="{% static 'scorecards/style.css' %}">
</head>
<body>

    {% block content %}

    <h3>Select round at {{ course.course_name }}:</h3>

    <hr />

    <div class="row">
        {% for round in rounds %}
        <!-- Print card for each round -->
        <div class="col-sm-3">
            <form action="." method="post">
                {% csrf_token %}
                <div class="card card-body" id="round_card">
                    <h4 class="card-title">{{ round.name }}</h4>
                    <p>Par: {{ round.total_par }}</p>
                    <input type="hidden" name="selected_round" value="{{ round }}" />
                    <input type="hidden" name="course" value="{{ course }}" />

                    <input class="btn btn-primary" type="submit" value="Select" />
                </div>
            </form>
        </div>
        {% endfor %}
    </div>
    
    {% endblock %}
</body>
</html>