StatiDisc/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [

    url(r'^courses/', include('courses.urls', namespace='courses')),

    url(r'^rounds/', include('rounds.urls', namespace='rounds')),

    url(r'^scorecards/', include('scorecards.urls', namespace='scorecards')),

    url(r'^admin/', admin.site.urls),

    url(r'^users/', include('users.urls', namespace='users')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'users'
urlpatterns = [
    # users/signup
    url(r'^signup/$', views.signup, name='signup'),

    # users/auth_user
    url(r'^auth_user', views.auth_user, name='auth_user'),

    # users/auth_user_logout
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    #users/5/profile
    url(r'^(?P<pk>\d+)/profile/$', views.profile_page, name='profile'),

    # users/social
    url(r'^social/$', views.social, name='social'),

    # users/add_friend
    url(r'^add_friend/$', views.add_friend, name='add_friend'),

    ]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Q
import operator

from scorecards.models import Scorecard, Score

# One-to-One link extending the user class for adding additional data and functions
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def get_no_of_rounds(self):
        scorecards = self.user.scorecard_set.all()
        return len(scorecards)

    # Get average score on a specific round
    def get_round_average(self, course, round):
        scorecards = get_scorecards_by_round(self, round, course)

        for scorecard  in scorecards:
            total_score += scorecard.total_score

        average = total_score / len(scorecards)
        return average

    # Get the average score on a single hole
    def get_hole_average(self, course, hole):
        scorecards = Scorecard.objects.filter(course = course, user = self.user)

        scores = []
        total_score = 0

        for scorecard in scorecards:
            try:
                scores.append(scorecard.score_set.get(hole = hole)) # Unsure if this will work
            except Score.DoesNotExist:
                # No score at this round
                go = None

        for score in scores:
            total_score += score.score

        # Avoid div by 0
        if total_score > 0:
            average = total_score / len(scores)
        else:
            average = 0
        return average

# QUERY FUNCTIONS #

    # Get scorecards by given course
    def get_scorecards_by_course(self, course, order = None):
        if order is None:
            scorecards = Scorecard.objects.filter(course = course, user = self.user)
        else:
            scorecards = Scorecard.objects.filter(course = course, user = self.user).order_by(order)
        return scorecards

    # Get scorecards by given round
    def get_scorecards_by_round(self, round, course, order = None):
        if order is None:
            scorecards = Scorecard.objects.get(round = round, course = course, user = self.user)
        else:
            scorecards = Scorecard.objects.filter(round = round, course = course, user = self.user).order_by(order)
        return scorecards
    
    # Get the most played course for a user
    def get_most_played_course(self):
        scorecards = Scorecard.objects.filter(user = self.user)

        statistics = dict()
        
        # Generate a dict with all played courses, extracting this info from the scorecards
        for scorecard in scorecards:
            course = scorecard.course
            # If course has entry in dict, add one to that index
            if course.course_name in statistics:
                statistics[course.course_name] += 1
            # Else, create that dict position and set to 1
            else:
                statistics[course.course_name] = 1

        max_course = max(statistics.items(), key=operator.itemgetter(1))[0]
        times = statistics[max_course]
        return max_course, times

    # Get friends of user
    def friends(self):
        return Friendship.objects.filter(Q(creator = self.user) | Q(friend = self.user)).all() # Get friendships where user is creator OR friend

# USER LINKAGE FUNCTIONS #

# Create profile object that is related to a created user object
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

# Save profile whenever the related user is saved
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

# Friendship model to model the friendship of two users
class Friendship(models.Model):
    created = models.DateTimeField(auto_now_add = True, editable = False)
    creator = models.ForeignKey(User, related_name='friendship_creator_set', on_delete=models.CASCADE)
    friend = models.ForeignKey(User, related_name='friend_set', on_delete=models.CASCADE)

users/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.forms import ModelForm
from django.urls import reverse_lazy, reverse
from django_tables2 import RequestConfig
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout

from .models import User
from scorecards.models import Score, Scorecard
from scorecards.forms import ScoreForm
from courses.models import Course, Hole
from rounds.models import Round
from courses.forms import HoleForm
from rounds.forms import RoundForm
from courses.tables import CourseTable, HoleTable
from scorecards.tables import ScoreCardTable, ScoreTable, ScoreCardTableMini
from rounds.tables import RoundTable

# Lets user sign up and create an account
def signup(request):
    # Create user
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user) # Manual authentication of user
            
            # Redirect user to start page
            courses = CourseTable(Course.objects.all())
            RequestConfig(request).configure(courses)

            noOfRounds = user.profile.get_no_of_rounds()
            scorecards = user.scorecard_set.order_by('-date_played')[0:4]
            most_played, times = user.profile.get_most_played_course()

            recent_scorecards = ScoreCardTableMini(scorecards)
            RequestConfig(request).configure(recent_scorecards)

            context = {'courses': courses, 
                       'noOfRounds': noOfRounds,
                       'recent_scorecards': recent_scorecards,
                       'most_played': most_played,
                       'times': times,
                       }
            return render(request, 'courses/index.html', context)
        # If something is not valid, post bound for with data and display errors
        else:
            context = {
            'form': form,
            }

            return render(request, 'users/signup.html', context)
    # Render user sign up form
    else:
        form = UserCreationForm()

        context = {
            'form': form,
            }

    return render(request, 'users/signup.html', context)

def auth_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)

            # Redirect user to start page
            courses = CourseTable(Course.objects.all())
            RequestConfig(request).configure(courses)

            noOfRounds = user.profile.get_no_of_rounds()
            scorecards = user.scorecard_set.order_by('-date_played')[0:4]
            most_played, times = user.profile.get_most_played_course()

            recent_scorecards = ScoreCardTableMini(scorecards)
            RequestConfig(request).configure(recent_scorecards)

            context = {'courses': courses, 
                       'noOfRounds': noOfRounds,
                       'recent_scorecards': recent_scorecards,
                       'most_played': most_played,
                       'times': times,
                       }
            return render(request, 'courses/index.html', context)
        # If user does not authenticate, redirect to sign up page
        else:
            error = 'You do not seem to have an account yet, sign up here'
            form = UserCreationForm()

            context = {
            'form': form,
            'error': error,
            }

            return render(request, 'users/signup.html', context)
    else:
        raise NotImplementedError

def profile_page(request, pk):
    if request.user.is_authenticated:
        profile_user = User.objects.get(id = pk)
        friends = profile_user.profile.friends()

        context = {
            'profile_user': profile_user,
            'friends': friends,

            }
        return render(request, 'users/profile.html', context)
    else:
        error = 'You do not seem to have an account yet, sign up here'
        form = UserCreationForm()

        context = {
        'form': form,
        'error': error,
        }

        return render(request, 'users/signup.html', context)

def social(request):
    if request.method == 'GET':
        if request.GET.get('search_input') is not None:
            search_val = request.GET.get('search_input')
            users = User.objects.filter(username__contains = search_val)

            return render(request, 'users/social.html', {'user_finds': users})
        else:
            return render(request, 'users/social.html')
    else:
        return render(request, 'users/social.html')

def add_friend(request):
    if request.method == 'POST':
        raise NotImplementedError('Not done yet')

users/templates/users/profile.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}
    
    <div class="row">
        <div class="col-sm-3">
            <div class="row">
                <div class="card card-body" style="margin-bottom: 10px">
                    <h5>Profile page for {{ profile_user }}</h5>
                    <hr />
                    <h5>Menu</h5>
                    <hr />
                    <form method="post" action="{% url 'users:add_friend' %}">
                        {% csrf_token %}
                        <input type="hidden" value="{{ profile_user }}" name="friend" />
                        <input class="btn btn-primary" type="submit" value="Add friend" />
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card card-body">
                {% if friends %}
                    <p>User has friends!</p>
                {% else %}
                    <p>Users has no friends yet!</p>
                {% endif %}
            </div>
        </div>
    </div>

    {% endblock %}

</body>
</html>

users/templates/users/signup.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}

    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}

    <div class="row">
        <div class="col-4">
            <div class="card card-body">

                <h2>Sign up for Statistical Disc!</h2>

                {% load widget_tweaks %}

                <form method="post" novalidate>
                    {% csrf_token %}

                    <!-- Display non-field related errors -->
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <!-- Render each form -->
                    {% for field in form %}
                    <div class="form-group">

                        <!-- Render tag for the field -->
                        {{ field.label_tag }}
                        
                        <!-- If form have data = it is bound, in that case -> render error for data in this form -->
                        {% if form.is_bound %}
                            {% if field.errors %}
                                {% render_field field class="form-control is-invalid" %}
                                {% for error in field.errors %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                                {% endfor %}
                            <!-- If this particular field is valid, but form is bound -> render green border -->
                            {% else %}
                                {% render_field field class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field field class="form-control" %}
                        {% endif %}

                        
                        <!-- Render field help text -->
                        {% if field.help_text %}
                        <small class="form-text text-muted">
                            {{ field.help_text|safe }}
                        </small>
                        {% endif %}

                        

                    </div>

                    {% endfor %}
                    
                    <button type="submit" class="btn btn-primary" style="width: 200px;">Create an account</button>
                </form>
                

            </div>
        </div>
    </div>
    
    {% endblock %}

</body>
</html>

users/templates/users/social.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}

    <div class="row">
        <div class="col-sm-3">
            <div class="card card-body">
                <h4>Find a player</h4>

                <form action="." method="get">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="search" name="search_input" placeholder="Search users..."/>
                        <input type="submit" value="Search" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            {% if user_finds %}
            <div class="card card-body">
                <h4>Search results</h4>
                
                {% for user in user_finds %}
                <p><a href="{% url 'users:profile' pk=user.id %}">{{ user }}</a></p>
                {% endfor %}

            </div>
            {% endif %}
        </div>
    </div>
    
    {% endblock %}

</body>
</html>