StatiDisc/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [

    url(r'^courses/', include('courses.urls', namespace='courses')),

    url(r'^rounds/', include('rounds.urls', namespace='rounds')),

    url(r'^scorecards/', include('scorecards.urls', namespace='scorecards')),

    url(r'^admin/', admin.site.urls),

    url(r'^users/', include('users.urls', namespace='users')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/urls.py
from django.conf.urls import url

from . import views


app_name = 'courses'
urlpatterns = [
    # courses/
    url(r'^$', views.index, name='index'),
    
    # courses/coursecreate
    url(r'^coursecreate/$', views.coursecreate.as_view(), name='coursecreate'),

    # courses/coursedetails/5
    url(r'^coursedetails/(?P<pk>\d+)/$', views.coursedetails, name='coursedetails'),

    # courses/addhole
    url(r'^coursedetails/(?P<pk>\d+)/addhole/$', views.addhole, name='addhole'),

    # courses/courseedit/5
    url(r'^courseedit/(?P<pk>\d+)/$', views.courseedit.as_view(), name='courseedit'),

    # courses/coursedelete/5
    url(r'^coursedetails/(?P<pk>\d+)/coursedelete/$', views.coursedelete.as_view(), name='coursedelete'),

    # courses/courseoverview/$
    url(r'^courseoverview/$', views.courseoverview, name='courseoverview'),

    #courses/holedetails/5
    url(r'^holedetails/(?P<pk>\d+)/$', views.holedetails, name='holedetails'),

    # courses/javascript_test_page/
    url(r'^javascript_test_page/$', views.javascript_test_page, name='javascript-test-page'),

    ]

scorecards/urls.py
from django.conf.urls import url

from . import views

app_name='scorecards'

urlpatterns = [
    
    # scorecards/
    url(r'^$', views.scorecards, name='scorecards'),

    # scorecards/fill_scorecard/$
    url(r'^fill_scorecard/$', views.fill_scorecard, name='fill_scorecard'),

    # scorecards/scorecarddetails/5/$
    url(r'^scorecarddetails/(?P<pk>\d+)/$', views.scorecarddetails, name='scorecarddetails'),

    # scorecards/5/select_round/$
    url(r'^(?P<pk>\d+)/select_round/$', views.select_round, name='select_round'),

    # scorecards/select_course/$
    url(r'^select_course/$', views.select_course, name='select_course'),
    ]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'users'
urlpatterns = [
    # users/signup
    url(r'^signup/$', views.signup, name='signup'),

    # users/auth_user
    url(r'^auth_user', views.auth_user, name='auth_user'),

    # users/auth_user_logout
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    #users/5/profile
    url(r'^(?P<pk>\d+)/profile/$', views.profile_page, name='profile'),

    # users/social
    url(r'^social/$', views.social, name='social'),

    # users/add_friend
    url(r'^add_friend/$', views.add_friend, name='add_friend'),

    ]

courses/models.py
from django.db import models
from django.urls import reverse
from datetime import date


# Define the course model
class Course(models.Model):
    course_name = models.CharField(max_length=200) # Name of course
    course_par = models.PositiveIntegerField(null=True) # Course total par
    course_location = models.CharField(max_length=200) # Location, like town or such for the course

    def __str__(self):
        return self.course_name

    def get_total_par(self):
        total_par = 0
        holes = self.hole_set.all()
        if holes:
            for hole in holes:
                total_par += hole.hole_par
            return total_par
        else:
            return total_par

    def get_absolute_url(self):
        return reverse('courses:coursedetails', kwargs={'pk': self.pk})

# Define the hole model
class Hole(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE) # Foreign key for a hole is a single course
    hole_number = models.PositiveIntegerField() # Hole number on the course
    hole_par = models.PositiveIntegerField() # Hole par
    hole_length = models.PositiveIntegerField() # Hole length in meters

    def __str__(self):
        return str(self.course)+ ", Hole: " + str(self.hole_number) # Display course and hole number

    def __unicode__(self):
        return str(self.hole_number)

courses/forms.py
from django import forms
from django.forms import ModelForm, ModelMultipleChoiceField

from .models import Hole, Course
from rounds.models import Round

class HoleForm(ModelForm):
    class Meta:
        model = Hole
        fields = ['hole_number', 'hole_par', 'hole_length']

# This form remains unused, using template CreateView in views.py instead
class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'course_par', 'course_location']

courses/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.forms import ModelForm
from django.urls import reverse_lazy, reverse
from django_tables2 import RequestConfig

from .models import Course, Hole
from scorecards.models import Score, Scorecard
from rounds.models import Round
from .forms import HoleForm
from rounds.forms import RoundForm
from .tables import CourseTable, HoleTable
from scorecards.tables import ScoreCardTable, ScoreTable, ScoreCardTableMini
from rounds.tables import RoundTable

# TODO:
# ASANA : https://app.asana.com/0/507127549374093/board

# Course index view, presents list over courses available in db
def index(request):
    courses = CourseTable(Course.objects.all())
    RequestConfig(request).configure(courses)

    if request.user.is_authenticated:
        user = request.user

        noOfRounds = user.profile.get_no_of_rounds()
        scorecards = user.scorecard_set.order_by('-date_played')[0:4]
        most_played, times = user.profile.get_most_played_course()

        recent_scorecards = ScoreCardTableMini(scorecards)
        RequestConfig(request).configure(recent_scorecards)

        context = {'courses': courses, 
                   'noOfRounds': noOfRounds,
                   'recent_scorecards': recent_scorecards,
                   'most_played': most_played,
                   'times': times,
                   }

        return render(request, 'courses/index.html', context)
    else:
        return render(request, 'courses/index.html', {'courses': courses})

# Rewritten course creator using Create-template out of Django
class coursecreate(generic.CreateView):
    model = Course
    template_name = 'courses/coursecreate.html'
    fields = ['course_name', 'course_location']
    
    # Set inital par to 0
    def form_valid(self, form):
        form.instance.course_par = 0 

        return super(coursecreate, self).form_valid(form)

# Let user edit course name, location and par
class courseedit(generic.UpdateView):
    model = Course
    fields = ['course_name', 'course_par', 'course_location']
    template_name = 'courses/courseedit.html'

# Let user delete course
class coursedelete(generic.DeleteView):
    model = Course
    template_name = 'courses/coursedelete.html'
    success_url = reverse_lazy('courses:index') # Go back to index view

# Create a course detail overview, showing holes and rounds
def coursedetails(request, pk):
    course = Course.objects.get(id=pk)
    holes = HoleTable(course.hole_set.all())
    rounds = RoundTable(course.round_set.all())
    context = {'holes': holes, 
               'course': course,
               'rounds': rounds,
               }
    RequestConfig(request, paginate={'per_page': 10}).configure(holes)
    return render(request, 'courses/coursedetails.html', context)

# When looking at coursedetails, user can add holes using this function. Checks if hole already exists so multiple holes doesnt get created
# THIS FUNCTION IS VERY STUPID!
def addhole(request, pk):
    if request.method == 'POST':
        course = Course.objects.get(id=pk)
        holeform = HoleForm(request.POST)
        new_hole = holeform.save(commit=False) # Create instance of object, DONT save to database
        new_hole.course_id = course.id
        check = 0;

        for hole in course.hole_set.all():
            if new_hole.hole_number == hole.hole_number: # Compare exisiting hole numbers to new one
                check = 1

        if check != 1: # If new hole, create and save
            new_hole.save()
            holetable = HoleTable(course.hole_set.all())
            form = HoleForm()

            # Update course's total_par
            course.course_par = course.get_total_par()
            course.save()

            context = {
                'hole': new_hole,
                'form': form,
                'holetable': holetable,
                'course': course,
            }
            return render(request, 'courses/addhole.html', context)
        elif check == 1:
            course = Course.objects.get(id=pk)
            holetable = HoleTable(course.hole_set.all())
            form = HoleForm()
            error = 'Hole already exists!' # Else return error string
            context = {
                    'course': course,
                    'form': form,
                    'error': error,
                    'holetable': holetable,
                }
            return render(request, 'courses/addhole.html', context)
    # If no POST, just return the view with course data
    else:
         course = Course.objects.get(id=pk)
         holetable = HoleTable(course.hole_set.all())
         form = HoleForm()
         context = {
                 'course': course,
                 'form': form,
                 'holetable': holetable,
                }
         return render(request, 'courses/addhole.html', context)

# Render list of courses
def courseoverview(request):
    table = CourseTable(Course.objects.all())
    RequestConfig(request).configure(table)
    return render(request, 'courses/courseoverview.html', {'table': table})
    
# Javascript test page render
def javascript_test_page(request):
    return render(request, 'courses/Javascript_test/javascript_test_page.html')

# Hole details
def holedetails(request, pk):
    hole = Hole.objects.get(id = pk)
    course = Course.objects.get(course_name = hole.course)

    if request.user.is_authenticated:
        user = request.user
        average_score = request.user.profile.get_hole_average(course, hole)

        context = {
        'hole': hole,
        'course': course,
        'average': average_score,
            }

        return render(request, 'courses/holedetails.html', context)

    context = {
        'hole': hole,
        'course': course,
        }
    return render(request, 'courses/holedetails.html', context)

courses/templates/courses/addhole.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>

    {% load render_table from django_tables2 %}

</head>
<body>

    {% block content %}

    <h3>Create a new hole for {{ course.course_name }}:</h3>

    {% render_table holetable %}

    <div class="form-group">
        <form action="." method="post">
            {% csrf_token %}


                <label>Hole number</label>
                {{ form.hole_number }}

                <label>Hole par</label>
                {{ form.hole_par }}


                <label>Hole length</label>
                {{ form.hole_length }}


            <input class="btn btn-primary" type="submit" value="Add!" style="margin-left: 10px;"/>

    </form>
    </div>
    {% if hole %}

    <div class="alert alert-success" role="alert" style="margin-top: 10px">
        Added hole {{ hole.hole_number }} to {{ course.course_name }}!
    </div>

    {% endif %}

    {% if error %}

    <div class="alert alert-danger" role="alert" style="margin-top: 10px">
        {{ error }}
    </div>

    {% endif %}

    {% endblock %}
</body>
</html>

courses/templates/courses/addscore.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}

    <h3>Add scores for scorecard:</h3>
    <p>Course: {{ scorecard.course }}</p>

    <form action="" method="post">
        {% csrf_token %}

        {% for form in score_form %}

        {{ form }}<br />

        {% endfor %}

        <input class="btn btn-primary" type="submit" value="Create!" />
    </form>

    {% endblock %}
</body>
</html>

courses/templates/courses/base.html
<html>

{% load static %}

<head>
    <title>StatisticalDisc</title>

    <!-- Load CSS, Bootstrap and fonts -->
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">
</head>
<body>

    <!-- Menu -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: cadetblue;">
        <a class="navbar-brand" href="/courses" style="font-family: 'Rubik', sans-serif;">StatiDisc</a>
        <!-- Navbar toggler if page is too small to show it all -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!-- Home button -->
                <li class="nav-item dropdown">
                    <a class="nav-link" href="/courses">Home<span class="sr-only">(current)</span></a>
                </li>
                <!-- Courses dropdown menu -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:courseoverview' %}">
                        Browse courses
                    </a>
                </li>
                <!-- Scorecard dropdown menu -->
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Scorecards
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'scorecards:scorecards' %}">Overview</a>
                            <a class="dropdown-item" href="{% url 'scorecards:select_course' %}">Create card</a>
                        </div>
                    </li>
                {% endif %}
                <!-- Test dropdown menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Test
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'courses:javascript-test-page' %}">JavaScript</a>
                        <a class="dropdown-item" href="#">Leaflet</a>
                    </div>
                </li>
                <!-- Some other links -->
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <div class="my-2 my-lg-0">
                <form method="post" action="/../users/logout/">
                    {% csrf_token %}

                    Logged in as: <a href="{% url 'users:profile' pk=user.id %}">{{ user.username }}</a>
                    <button type="submit" class="btn btn-primary btn-sm" style="background-color: black; padding-left: 10px;">Log out</button> <!-- This part needs fix! -->
                </form>
            </div>
            {% else %}
            <form method="POST" action="/users/auth_user" class="form-inline ml-auto">
                {% csrf_token %}

                <input class="form-control form-control-sm ml-2" name="username" type="text" placeholder="Username">
                <input class="form-control form-control-sm ml-2" name="password" type="password" placeholder="Password">
                <button class="btn btn-primary btn-sm ml-2" type="submit" style="background-color: black">Log in</button>
            </form>
            {% endif %}
        </div>
    </nav>

    <!-- Render body -->
    <div class="container-fluid" style="padding-top: 10px">
        <!-- Content block -->
        {% block content %}


        {% endblock %}

        <!-- Footer -->
        <footer>
            <div class="footer">
                <p class="text-muted" style="font-size: 14px">StatiDisc build 2017</p>
            </div>
        </footer>
    </div>

    <!-- Load JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js" integrity="sha384-feJI7QwhOS+hwpX2zkaeJQjeiwlhOP+SdQDqhgvvo1DsjtiSQByFdThsxO669S2D" crossorigin="anonymous"></script>
    
    <!-- Block for including scripts on pages -->
    {% block scripts %}

    {% endblock %}

</body>
</html>

courses/templates/courses/coursecreate.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}

    <h3>Create a new course:</h3>

    <hr />

    <form action="" method="post">
        {% csrf_token %}
        
        {{ form.as_p}}

        <input class="btn btn-primary" type="submit" value="Create!" />
    </form>

    {% endblock %}
</body>
</html>

courses/templates/courses/coursedelete.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}

    <h2>Do you want to delete {{ course.course_name }}?</h2>

    <form action="" method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <input class="btn btn-danger" type="submit" value="Yes!" /> <a href="/courses/coursedetails/{{ course.id }}" class="btn btn-success" >No!</a>


    </form>

    {% endblock %}
</body>
</html>

courses/templates/courses/coursedetails.html
<!DOCTYPE html>

    {% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>{{ course.course_name }} details</title>

    {% load render_table from django_tables2 %}

</head>
<body>

    {% block content %}

    <div class="row">
        <div class="col-3">
            <div class="row">
                <div class="col">
                    <!-- Course information card -->
                    <div class="card card-body">
                        <h2 class="card-title">{{ course.course_name }}</h2>
                        <h5><b>Information:</b></h5>
                        <br />
                        <h5>Total par: {{ course.course_par }}</h5>
                        <h5>Location: {{ course.course_location }}</h5>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col" style="padding-top: 10px">
                    <!-- Menu for course -->
                    <div class="card card-body">
                        <h4 class="card-title">Menu:</h4>
                        <a class="btn btn-primary" href="addhole">Add a hole</a><hr />
                        <a class="btn btn-primary" href="/rounds/{{ course.id }}/createround">Create round!</a><hr />
                        <a class="btn btn-primary" href="/scorecards/{{ course.id }}/select_round">Create scorecard!</a><hr />
                        <a class="btn btn-primary" href="coursedelete">Delete course!</a><hr />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-5" style="padding-left: 10px">
            <!-- Hole list -->
            <div class="card card-body">
                <h2>Holes</h2>

                {% render_table holes %}
            </div>
        </div>
        <div class="col-4">
            <!-- Round list -->
            <div class="card card-body">
                <h2>Rounds</h2>

                {% render_table rounds %}
            </div> 
        </div>
    </div>
    {% endblock %}
</body>
</html>

courses/templates/courses/courseedit.html
<!DOCTYPE html>

    {% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    {% block content %}

    <form action="" method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Edit!" />


    </form>

    {% endblock %}

</body>
</html>

courses/templates/courses/courseoverview.html
<!DOCTYPE html>
    {% extends 'courses/base.html' %}
{% load render_table from django_tables2 %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Courses</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
    
    {% block content %}

    <h2>All courses:</h2>

	{% render_table table %}

    {% endblock %}
</body>
</html>

courses/templates/courses/holedetails.html
<!DOCTYPE html>

    {% extends 'courses/base.html' %}

    {% load static %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>{{ course.course_name }} details</title>

    {% load render_table from django_tables2 %}

</head>
<body>

    {% block content %}

    <div class="row">
        <div class="col-sm-3">
            <div class="card card-body">
                <h4 class="card-title">Hole {{ hole.hole_number }}, {{ course.course_name }}</h4>
                <hr />
                <p>Hole length: {{ hole.hole_length }}</p>
                <p>Hole par: {{ hole.hole_par }}</p>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="card card-body">
                <h3>Cool hole map!</h3>
                <img src="{% static '/images/yato_error.jpg' %}" />
            </div>
        </div>
        {% if user.is_authenticated %}
        <div class="col-sm-4">
            <div class="card card-body">
                <h4>Your stats on this hole</h4>
                Your average score: {{ average }}
            </div>
        </div>

        {% endif %}
    </div>
        
    {% endblock %}
</body>
</html>

courses/templates/courses/index.html
<!DOCTYPE html>

{% extends 'courses/base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

{% load static %}

<head>
    <meta charset="utf-8" />
    <title>StatiDisc</title>

    {% load render_table from django_tables2 %}

</head>
<body>

    {% block content %}

        <div class="row">
            <!-- Welcome card -->
            <div class="col-sm-6">
                <div class="card card-body">
                    <div class="row">
                        <h2 class="card-title">Welcome to Statistical Disc</h2>
                        <p>
                            Statistical Disc is a discgolf page for you to keep track of scorecards, statistics and courses all around the world! It is a project I
                            develop in my spare time to learn Django development as well as HTML, CSS and JavaScript.
                        </p>
                    </div>
                    <hr />
                    <!-- Featured courses caurosel -->
                    <div class="row">
                        <h3 class="card-title">Featured courses</h3>
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <!-- Kärsön slide -->
                                <div class="carousel-item active">
                                    <a href="/courses/coursedetails/11/"><img class="d-block w-100" src="{% static '/images/Karson.jpg' %}" alt="First slide"></a>
                                    <div class="carousel-caption d-none d-md-block">
                                        <h3>Kärsön Discgolfbana</h3>
                                    </div>
                                </div>
                                <!-- Järva slide -->
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/images/Jarva.jpg' %}" alt="Second slide">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h3>Järva Discgolfpark</h3>
                                    </div>
                                </div>
                                <!-- Visättra slide -->
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/images/Visattra.jpg' %}" alt="Third slide">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h3>Visättra Discgolfbana</h3>
                                    </div>
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                {% if user.is_authenticated %}
                <div class="row" style="padding-bottom: 10px">
                    <div class="col">
                        <div class="card card-body">
                            <h3 class="card-title">Welcome {{ user }}!</h3>
                            <p>You have played {{ noOfRounds }} rounds. Your most played course is {{ most_played }} 
                            at which you have played a total {{ times }} of times. </p>
                            <h5>Your latest rounds:</h5>
                            {% render_table recent_scorecards %}
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- Course table -->
                <div class="row" style="padding-bottom: 10px">
                    <div class="col">
                        <div class="card card-body">
                            <h3>Courses</h3>

                            {% render_table courses%}

                            <hr />

                        </div>
                    </div>
                </div>
                <!-- My TODO list -->
                <div class="row" style="padding-bottom: 10px">
                    <div class="col">
                        <div class="card card-body" style="background-color: aquamarine; ">
                            <h6># TODO : </h6>
                            <ul>
                                <li>Add breakpoints on every column/card, so that it suits mobile</li>
                                <li>More statistics for course/rounds, played cards on that round/course and so on</li>
                                <li>Try out the "most played"-function</li>
                                <li>Start looking into mobile rendering of scorecard creation</li>
                                <li>Add link to sign up-page</li>
                                <li>Add next hole/prev hole when vieweing holedetails for easier navigation</li>
                                <li>Maybe redo the scorecard form, maybe one form then render new page and so on</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endblock %}
</body>
</html>